"use client";
import {useState} from "react"; import {MapPin,Car,ShieldCheck,Wrench,Siren,ChevronRight,Star,Navigation} from "lucide-react";
const jobs=["Engine won't start","Flat tyre","Battery problem","Overheating","Electrical fault","Diagnostics","Oil/service","Accident/recovery"];
export default function Home(){const [problem,setProblem]=useState(""); const [role,setRole]=useState("driver"); return <main>
<header><div className="brand"><span className="mark"><Wrench size={20}/></span><b>MECHANICS</b></div><nav><a>How it works</a><a>For Mechanics</a><a>Safety</a><button className="outline">Sign in</button><button>Get help</button></nav></header>
<section className="hero"><div className="copy"><div className="pill"><span/>24/7 roadside assistance</div><h1>When your car stops,<br/><em>help moves.</em></h1><p>Connect with a verified mechanic near you. Tell us what happened and we'll help you find the right person, wherever you are.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById("request")?.scrollIntoView({behavior:"smooth"})}><Siren size={19}/> Request a mechanic <ChevronRight size={18}/></button><button className="secondary">I’m a mechanic <ChevronRight size={17}/></button></div><div className="trust"><ShieldCheck size={18}/><span>Verified mechanics</span><span>•</span><span>Live location</span><span>•</span><span>Secure payments</span></div></div>
<div className="map"><div className="maptop"><div><MapPin size={17}/> <span>Your location</span></div><span className="live">● LIVE</span></div><div className="mapgrid"><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="pin p1"><Wrench/></div><div className="pin p2"><Wrench/></div><div className="pin p3"><Wrench/></div><div className="you"><span/></div><div className="maplabel"><Navigation size={15}/><div><b>3 mechanics nearby</b><small>Within 5 km</small></div></div></div></div></section>
<section id="request" className="request"><div className="sectionhead"><div><div className="eyebrow">NEED HELP?</div><h2>Find a mechanic now</h2></div><div className="role"><button className={role==="driver"?"active":""} onClick={()=>setRole("driver")}>Driver</button><button className={role==="mechanic"?"active":""} onClick={()=>setRole("mechanic")}>Mechanic</button></div></div>
{role==="driver"?<div className="card"><div className="field"><label>Where are you?</label><div className="input"><MapPin size={18}/><span>Use my current location</span><b>GPS</b></div></div><div className="field"><label>What's wrong?</label><div className="jobs">{jobs.map(x=><button key={x} className={problem===x?"selected":""} onClick={()=>setProblem(x)}>{x}</button>)}</div></div><div className="row"><div className="field"><label>Vehicle</label><div className="input"><Car size={18}/><span>Toyota · Select vehicle</span></div></div><button className="find"><Siren size={18}/> Find nearby mechanics</button></div></div>:<div className="card mechaniccard"><Wrench size={30}/><div><h3>Join the mechanic network</h3><p>Receive nearby jobs, manage your availability and grow your customer base.</p></div><button className="find">Register as a mechanic <ChevronRight/></button></div>}</section>
<section className="features"><div><ShieldCheck/><h3>Verified professionals</h3><p>Mechanics can be verified before joining the network.</p></div><div><MapPin/><h3>Location matching</h3><p>Find available help based on distance and service type.</p></div><div><Star/><h3>Trusted by ratings</h3><p>Build confidence with transparent reviews and job history.</p></div></section>
<footer><b>MECHANICS</b><span>Roadside assistance marketplace</span><span>© 2026 Mechanics</span></footer>
</main>}