export type Mechanic = { id:string; full_name:string; business_name:string; specialties:string[]; service_radius_km:number; latitude:number; longitude:number; verified:boolean; rating_average:number; rating_count:number; };
export type Job = { id:string; mechanic_id:string; service_type:string; status:string; customer_id:string; };
export type Rating = { id:string; job_id:string; mechanic_id:string; service_type:string; rating:number; review:string|null; recommended:boolean; created_at:string; };
const seedMechanics:Mechanic[]=[
{id:"mech-001",full_name:"Kevin Ochieng",business_name:"Ochieng Auto Rescue",specialties:["Engine & diagnostics","Electrical systems","Battery & starting"],service_radius_km:15,latitude:-0.0917,longitude:34.7680,verified:true,rating_average:4.8,rating_count:24},
{id:"mech-002",full_name:"Brian Otieno",business_name:"Lakeview Motor Care",specialties:["Tyres & punctures","Brakes & suspension","Cooling & overheating"],service_radius_km:12,latitude:-0.1022,longitude:34.7617,verified:true,rating_average:4.6,rating_count:18},
{id:"mech-003",full_name:"Samuel Onyango",business_name:"West Kenya Mobile Mechanics",specialties:["Engine & diagnostics","Transmission","Vehicle recovery"],service_radius_km:20,latitude:-0.0789,longitude:34.7510,verified:true,rating_average:4.5,rating_count:31}],
const seedJobs:Job[]=[{id:"job-demo-001",mechanic_id:"mech-001",service_type:"Engine & diagnostics",status:"completed",customer_id:"customer-demo-001"},{id:"job-demo-002",mechanic_id:"mech-002",service_type:"Flat tyre / tyre repair",status:"completed",customer_id:"customer-demo-002"},{id:"job-demo-003",mechanic_id:"mech-003",service_type:"Recovery / towing",status:"completed",customer_id:"customer-demo-003"}];
const seedRatings:Rating[]=[{id:"rating-001",job_id:"job-old-001",mechanic_id:"mech-001",service_type:"Engine & diagnostics",rating:5,review:"Fast response and the repair was explained clearly.",recommended:true,created_at:"2026-08-28T10:00:00Z"},{id:"rating-002",job_id:"job-old-002",mechanic_id:"mech-001",service_type:"Battery / starting",rating:5,review:"Arrived quickly and got the car started.",recommended:true,created_at:"2026-08-21T08:30:00Z"},{id:"rating-003",job_id:"job-old-003",mechanic_id:"mech-002",service_type:"Brakes & suspension",rating:5,review:"Professional mobile service.",recommended:true,created_at:"2026-08-25T14:00:00Z"}];
const g=globalThis as typeof globalThis & {__mechanicsStore?:{mechanics:Mechanic[];jobs:Job[];ratings:Rating[]}};
if(!g.__mechanicsStore)g.__mechanicsStore={mechanics:seedMechanics,jobs:seedJobs,ratings:seedRatings};
export const mechanicsStore=g.__mechanicsStore;
export function refreshRating(id:string){const m=mechanicsStore.mechanics.find(x=>x.id===id);if(!m)return;const r=mechanicsStore.ratings.filter(x=>x.mechanic_id===id);m.rating_count=r.length;m.rating_average=r.length?Math.round(r.reduce((s,x)=>s+x.rating,0)/r.length*100)/100:0;}